### ISSUE TITLE
implement add-to-cart functionality

### ISSUE THREAD

**Issue by dboatengg** [dboatengg/ecommerce-product-page#3]
Add to cart functionality is not currently working.

**Comment by munenelewis** [comment]
Hey @dboatengg worked on this you can check the changes [#4 ](https://github.com/dboatengg/ecommerce-product-page/pull/4#issue-1789118283)

**Comment by dboatengg** [comment]
Looks good!

**Comment by dboatengg** [comment]
Fixed!
